package me.jdan.dao;

import java.util.List;
import me.jdan.po.Newscategory;
import me.jdan.po.NewscategoryExample;
import org.apache.ibatis.annotations.Param;

public interface NewscategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int countByExample(NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int deleteByExample(NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int insert(Newscategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int insertSelective(Newscategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    List<Newscategory> selectByExample(NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    Newscategory selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") Newscategory record, @Param("example") NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int updateByExample(@Param("record") Newscategory record, @Param("example") NewscategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int updateByPrimaryKeySelective(Newscategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newscategory
     *
     * @mbggenerated Sun May 28 11:20:05 CST 2017
     */
    int updateByPrimaryKey(Newscategory record);

    /*
    * write by author
    * */
    List<Newscategory> selectAllNewsCategory();
    List<Newscategory> selectAllSubNewsCategory();
    List<Newscategory> selectAllFirstLevelNewsCategory();
    List<Newscategory> selectSubNewsCategoryBySuperId(int id);
    List<Newscategory> selectCategoryByName(String name);
}